[package]
name = "askr"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.14"
env_logger = "0.9.0"
bytes ="1"
atoi = "1.0.0"
thiserror = "1.0.30"
memmap2 = "0.5.3"